### ISSUE TITLE
Slider Stuff

### ISSUE THREAD

**Issue by fpunny** [cheapreats/react-ui-library#83]
# Goals

 - Help you develop a certain way of thinking when creating React components to help improve quality and quantity of code you produce
 - To make something which at the end of the day, you can be proud of and show an employeer/loved one/pet fish
 - For me to be better at teaching stuff
 - For me to get my component

# Inspiration
https://uimovement.com/design/color-slider/

# Tasks
I would have a list of tasks for you to complete, which you would comment to work on them one by one (We don't do the next one until the last one is complete, which is done by me reviewing your comment and ticking it off this list)

- [x] **Break down the mockup into HTML.** What are the elements needed to create this? How are the working together?
- [x] **The interactions.** What JS would we need to handle the interactions that are happening?
- [ ] **The react.** How are we going to organize the HTML and interactions into component(s)? What states do we need? What effects? What refs?
- [ ] **The API.** What props is this component going to take? What are their types? Why do we need this prop?
- [ ] **The styling.** How would we style this? What do we need to add to themes? What do we use from themes? What mixins are we going to use?
- [ ] **Implement it.** I'll add to this when we get there

# Points

1. but lots of the properties will be similar, for example all the three bars will have the same width and height... can I give em different ids like what I did with thumbs?:

```
<div class="bar" id="mainbar">
  <div class="bar" id="selectedbar"></div>
  <div class="thumb" id="start"></div>
  <div class="thumb" id="end"></div>
</div>

<div  class="bar" "marksbar"></div>
```

2. As a user, I should be able to adjust the left knob such that I can change the lower bound
As a user, I should be able to adjust the right knob such that I can change the higher bound

if not I think we should add these:
As a user, I should be able to disable the component such that nothing happens after clicking the component
As a user, I should be able to set a maximum value such that the knob doesn't go further than that point to the right
As a user, I should be able to set a minimum value such that the knob has at least that point to the left
As a user, I should be able to set a step value such that the knobs move through those steps when adjusting them

**Comment by sahandfarahani** [comment]
Thank you Fred for helping me through this process well as for 
Break down the mockup into HTML. What are the elements needed to create this? How are the working together?
3 Bars:
1)To be the background of the process and move the thumbs on it
2)To mark the selected Area
3)To put marks under the main bar if necessary

2 Thumbs:
1)Mandatory when start of selected area is 0 and can't be changed
2)Optional when user needs to change the start of the selected area as well

1 Popup bubble: Optional to show the current value of the thumb on the track

**Comment by sahandfarahani** [comment]
should I answer all the questions at once or should we go step by step?

**Comment by fpunny** [comment]
@sahandfarahani We'll do this one by one. Can you write some HTML, or psuedo HTML, do show it? :3

**Comment by sahandfarahani** [comment]
> 
> 
> Can you write some HTML, or psuedo HTML, do show it? :3
> 

you mean write the HTML just to put the elements in the page?

**Comment by sahandfarahani** [comment]
like this? :

<style>
.bar{
  width: 100%;
  height: 4px;
  background: #e9e9e9;
  display:flex;
  }
  
.thumb{
  width: 14px;
  height: 14px;
  background: red;
  border-radius: 50%;
  position:absolute;
  }
  
  #start{
    left=1px;
  }
  
  #end{
    left:100px;
  }

</style>

<div class="bar">
  <div class="bar"></div>
  <div class="thumb" id="start"></div>
  <div class="thumb" id="end"></div>
</div>

<div  class="bar"></div>

**Comment by sahandfarahani** [comment]
like this? :

<style>

.bar{
  width: 100%;
  height: 4px;
  background: #e9e9e9;
  display:flex;
  }
  
.thumb{
  width: 14px;
  height: 14px;
  background: red;
  border-radius: 50%;
  position:absolute;
  }
  
  #start{
    left=1px;
  }
  
  #end{
    left:100px;
  }

</style>

<div class="bar">
  <div class="bar"></div>
  <div class="thumb" id="start"></div>
  <div class="thumb" id="end"></div>
</div>

<div  class="bar"></div>

**Comment by sahandfarahani** [comment]
<div class="bar">
  <div class="bar"></div>
  <div class="thumb" id="start"></div>
  <div class="thumb" id="end"></div>
</div>

<div  class="bar"></div>

**Comment by sahandfarahani** [comment]
<div class="bar">
  <div class="bar"></div>
  <div class="thumb" id="start"></div>
  <div class="thumb" id="end"></div>
</div>

<div  class="bar"></div>

**Comment by sahandfarahani** [comment]
```
<div class="bar">
  <div class="bar"></div>
  <div class="thumb" id="start"></div>
  <div class="thumb" id="end"></div>
</div>

<div  class="bar"></div>
```
CSS
```
.bar{
  width: 100%;
  height: 4px;
  background: #e9e9e9;
  display:flex;
  }
  
.thumb{
  width: 14px;
  height: 14px;
  background: red;
  border-radius: 50%;
  position:absolute;
  }
  
  #start{
    left=1px;
  }
  
  #end{
    left:100px;
  }
```

**Comment by sahandfarahani** [comment]
Well I thought because the thumbs are moving inside the bar & the select bar is filling inside the main bar it would be logical to put them inside the div 
and the last bar which contains the captions, since it is shown under the bar I should put it after the main bar and all the captions inside of it

**Comment by fpunny** [comment]
> Well I thought because the thumbs are moving inside the bar & the select bar is filling inside the main bar it would be logical to put them inside the div
> and the last bar which contains the captions, since it is shown under the bar I should put it after the main bar and all the captions inside of it

Hmm okay, can we have some better class names to represent them? As it stands now, if I were to look at the just the HTML, they all look the same

**Comment by sahandfarahani** [comment]
like this?
<div class="bar">
  <div class="selectedbar"></div>
  <div class="thumb" id="start"></div>
  <div class="thumb" id="end"></div>
</div>

<div  class="markingbar"></div>

**Comment by sahandfarahani** [comment]
but lots of the properties will be similar, for example all the three bars will have the same width and height... can I give em different ids like what I did with thumbs?:
```
<div class="bar" id="mainbar">
  <div class="bar" id="selectedbar"></div>
  <div class="thumb" id="start"></div>
  <div class="thumb" id="end"></div>
</div>

<div  class="bar" "marksbar"></div>
```

**Comment by sahandfarahani** [comment]
@fpunny sorry I forgot to mention your name

**Comment by fpunny** [comment]
Okay looks good, now lets talk about the interactions. Here's an example
- As a user, I should be able to adjust the left knob such that I can change the lower bound
- As a user, I [insert action] such that [why do I need this]

**Comment by sahandfarahani** [comment]
@fpunny 
user as someone who is using the component in a form and such? or user as customer?
if it's user as customer I think it will be only:
As a user, I should be able to adjust the left knob such that I can change the lower bound
As a user, I should be able to adjust the right knob such that I can change the higher bound

if not I think we should add these:
As a user, I should be able to disable the component such that nothing happens after clicking the component
As a user, I should be able to set a maximum value such that the knob doesn't go further than that point to the right
As a user, I should be able to set a minimum value such that the knob has at least that point to the left
As a user, I should be able to set a step value such that the knobs move through those steps when adjusting them

**Comment by sahandfarahani** [comment]
@fpunny  
The react. How are we going to organize the HTML and interactions into component(s)? What states do we need? What effects? What refs?

so I have to use divs and 'styled' feature to make them as react components... in the styled components I'll have to set the properties to make sure the children will be positioned at the proper place relative to the parent bar

the states which would change should be 2 values , 1 for left knob and 2 for right knob so that with changing their position these states change

as for effects I need a uselayouteffect rather than useeffect to set the default properties to the components because when using uselayouteffect, the components are mounted already on the screen

as for refs I used 1 ref to reference the parent bar and calculated it's relations to find other bars and knobs... but I guess if I use 1 ref per component I can avoid the calculations ... (?)

**Comment by sahandfarahani** [comment]
@fpunny 
The API. What props is this component going to take? What are their types? Why do we need this prop?

max : number  > to get put at the right of the bar so that the knob can’t exceed to the right of the bar

min: number > to get put at the left of the bar so that the knob can’t exceed to the left of the bar

step: number > so that the knobs move through these steps

disabled: boolean > in case of being true color of the bar go grey and nothing would happen when clicking it

rail: boolean > in case of being true the space between the left knob and right knob will be highlighted

twoInputs: boolean > in case of being true we will have two knobs otherwise the start point of the bar will be set to min prop and only the right knob will appear

value: number > the default position of the right knob on the bar

valueStart: number > the default position of the left knob on the bar in case twoInputs prop is set to true

marks [key: number, mark: string] > array of marks which will be set on the markbar under the main bar, key will present the value which the mark should be placed at, and mark will be what the user wants to be shown on the certain value

**Comment by sahandfarahani** [comment]
@fpunny 
The styling. How would we style this? What do we need to add to themes? What do we use from themes? What mixins are we going to use?

For the knobs we are going to use text color primary.

For the selectedBar we are going to use text color primary.

For the mainBar we are going to use #e9e9e9 as backroundcolor.

Border Radius for mainBar and selectedBar is going to be theme.dimensions.radius

Box-Shadow for mainBar and selectedBar is going to be theme.depth[1]

**Comment by ralph-dev** [comment]
@sahandfarahani @fpunny are you two working on this on Github or on the Confluence document over here? 
Link: https://wolfbeacon.atlassian.net/wiki/spaces/CW/pages/1210024194/Making+a+Slider+Component
